
theme: jekyll-theme-minimal
title: My Portfolio
description: I am an undergraduate at the University of Florida who is studying physics and nuclear engineering. An avid experimentalist, I have numerous projects which display both my engineering skills and hands on technical skills. 
![](Headshot.jpg)
Author: Elliott Hirko
